# Uncomment the next line to define a global platform for your project
platform :ios, '11.4'

target 'StoreApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftLint'
  pod 'Toaster'
  pod 'Alamofire', '~> 4.7'

  # Pods for StoreApp

  target 'StoreAppUnitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
